wip

diff --git a/install-configs b/install-configs
--- a/install-configs
+++ b/install-configs
@@ -1,7 +1,14 @@
 #!/usr/bin/env bash
 
+catch() {
+	echo "Error $1 occurred in line $2"
+	return "$1"
+}
+
+trap 'catch $? $LINENO' ERR
+
 set -e
-# set -u
+set -u
 set -o pipefail
 
 BASE_CONFIG="base"
@@ -9,7 +16,6 @@ CONFIG_SUFFIX=".yaml"
 
 META_DIR="meta"
 CONFIG_DIR="configs"
-PROFILES_DIR="profiles"
 
 DOTBOT_DIR="dotbot"
 DOTBOT_BIN="bin/dotbot"
@@ -18,21 +24,15 @@ BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 PLUGINS_DIR="plugins"
 
-PROFILE_NAME=${1:-?}
-
 DOTBOT_BIN="bin/dotbot"
 
 cd "${BASE_DIR}"
-git submodule update --init --recursive --remote
+git submodule update --init --recursive
 
-while IFS= read -r config; do
-	CONFIGS+=" ${config}"
-done <"${META_DIR}/${PROFILES_DIR}/${PROFILE_NAME}"
+CONFIGS=$(echo "${@}" | sed -r ':a; s/\b([[:alnum:]]+)\b(.*)\b\1\b/\1\2/g; ta; s/(, )+/, /g; s/, *$//')
 
-shift
-
-for config in ${CONFIGS} "${@}"; do
-	echo -e "\nConfigure ${config}"
+for config in ${CONFIGS}; do
+	[[ -f ${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX} ]] || echo
 	configContent="$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")"
 	"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
 		--plugin-dir "${META_DIR}"/"${PLUGINS_DIR}"/dotbot-snap \
@@ -40,8 +40,3 @@ for config in ${CONFIGS} "${@}"; do
 		-d "${BASE_DIR}" \
 		-c <(echo -e "${configContent}")
 done
-
-# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"  \
-#   --plugin-dir plugins/dotbot-snap \
-#   --plugin-dir plugins/dotbot-template \
-# "${@}"
